/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.desko.fullpage;

public class DebugHandler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public DebugHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DebugHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PageScanApiJNI.delete_DebugHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    PageScanApiJNI.DebugHandler_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    PageScanApiJNI.DebugHandler_change_ownership(this, swigCPtr, true);
  }

  public void OnEvent(int Timestamp, String Thread, String Domain, int Level, String Function, String Message) {
    if (getClass() == DebugHandler.class) PageScanApiJNI.DebugHandler_OnEvent(swigCPtr, this, Timestamp, Thread, Domain, Level, Function, Message); else PageScanApiJNI.DebugHandler_OnEventSwigExplicitDebugHandler(swigCPtr, this, Timestamp, Thread, Domain, Level, Function, Message);
  }

  public DebugHandler() {
    this(PageScanApiJNI.new_DebugHandler(), true);
    PageScanApiJNI.DebugHandler_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
