/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.desko.fullpage;

public class OnDevicePlugHandler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OnDevicePlugHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OnDevicePlugHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PageScanApiJNI.delete_OnDevicePlugHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    PageScanApiJNI.OnDevicePlugHandler_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    PageScanApiJNI.OnDevicePlugHandler_change_ownership(this, swigCPtr, true);
  }

  public void OnEvent(boolean plugged) {
    if (getClass() == OnDevicePlugHandler.class) PageScanApiJNI.OnDevicePlugHandler_OnEvent(swigCPtr, this, plugged); else PageScanApiJNI.OnDevicePlugHandler_OnEventSwigExplicitOnDevicePlugHandler(swigCPtr, this, plugged);
  }

  public OnDevicePlugHandler() {
    this(PageScanApiJNI.new_OnDevicePlugHandler(), true);
    PageScanApiJNI.OnDevicePlugHandler_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
