/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.desko.fullpage;

public class OnTouchDisplayHandler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OnTouchDisplayHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OnTouchDisplayHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PageScanApiJNI.delete_OnTouchDisplayHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    PageScanApiJNI.OnTouchDisplayHandler_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    PageScanApiJNI.OnTouchDisplayHandler_change_ownership(this, swigCPtr, true);
  }

  public void OnEvent(int TouchDown, float RelativeX, float RelativeY) {
    if (getClass() == OnTouchDisplayHandler.class) PageScanApiJNI.OnTouchDisplayHandler_OnEvent(swigCPtr, this, TouchDown, RelativeX, RelativeY); else PageScanApiJNI.OnTouchDisplayHandler_OnEventSwigExplicitOnTouchDisplayHandler(swigCPtr, this, TouchDown, RelativeX, RelativeY);
  }

  public OnTouchDisplayHandler() {
    this(PageScanApiJNI.new_OnTouchDisplayHandler(), true);
    PageScanApiJNI.OnTouchDisplayHandler_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
