/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.desko.fullpage;

public class TPSAScanSettings {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public TPSAScanSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TPSAScanSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PageScanApiJNI.delete_TPSAScanSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setScanIRLight(boolean value) {
    PageScanApiJNI.TPSAScanSettings_ScanIRLight_set(swigCPtr, this, value);
  }

  public boolean getScanIRLight() {
    return PageScanApiJNI.TPSAScanSettings_ScanIRLight_get(swigCPtr, this);
  }

  public void setScanUvOnlyLight(boolean value) {
    PageScanApiJNI.TPSAScanSettings_ScanUvOnlyLight_set(swigCPtr, this, value);
  }

  public boolean getScanUvOnlyLight() {
    return PageScanApiJNI.TPSAScanSettings_ScanUvOnlyLight_get(swigCPtr, this);
  }

  public void setScanUV3Light(boolean value) {
    PageScanApiJNI.TPSAScanSettings_ScanUV3Light_set(swigCPtr, this, value);
  }

  public boolean getScanUV3Light() {
    return PageScanApiJNI.TPSAScanSettings_ScanUV3Light_get(swigCPtr, this);
  }

  public void setScanVisibleLight(boolean value) {
    PageScanApiJNI.TPSAScanSettings_ScanVisibleLight_set(swigCPtr, this, value);
  }

  public boolean getScanVisibleLight() {
    return PageScanApiJNI.TPSAScanSettings_ScanVisibleLight_get(swigCPtr, this);
  }

  public void setResolution(long value) {
    PageScanApiJNI.TPSAScanSettings_Resolution_set(swigCPtr, this, value);
  }

  public long getResolution() {
    return PageScanApiJNI.TPSAScanSettings_Resolution_get(swigCPtr, this);
  }

  public TPSAScanSettings() {
    this(PageScanApiJNI.new_TPSAScanSettings(), true);
  }

}
