/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.desko.fullpage;

public class TPSADeviceInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public TPSADeviceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TPSADeviceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PageScanApiJNI.delete_TPSADeviceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCompileDate(String value) {
    PageScanApiJNI.TPSADeviceInfo_CompileDate_set(swigCPtr, this, value);
  }

  public String getCompileDate() {
    return PageScanApiJNI.TPSADeviceInfo_CompileDate_get(swigCPtr, this);
  }

  public void setCompileTime(String value) {
    PageScanApiJNI.TPSADeviceInfo_CompileTime_set(swigCPtr, this, value);
  }

  public String getCompileTime() {
    return PageScanApiJNI.TPSADeviceInfo_CompileTime_get(swigCPtr, this);
  }

  public void setSupport_UV(boolean value) {
    PageScanApiJNI.TPSADeviceInfo_Support_UV_set(swigCPtr, this, value);
  }

  public boolean getSupport_UV() {
    return PageScanApiJNI.TPSADeviceInfo_Support_UV_get(swigCPtr, this);
  }

  public void setSupport_Color(boolean value) {
    PageScanApiJNI.TPSADeviceInfo_Support_Color_set(swigCPtr, this, value);
  }

  public boolean getSupport_Color() {
    return PageScanApiJNI.TPSADeviceInfo_Support_Color_get(swigCPtr, this);
  }

  public void setSupport_Barcode(boolean value) {
    PageScanApiJNI.TPSADeviceInfo_Support_Barcode_set(swigCPtr, this, value);
  }

  public boolean getSupport_Barcode() {
    return PageScanApiJNI.TPSADeviceInfo_Support_Barcode_get(swigCPtr, this);
  }

  public void setSupport_MSR(boolean value) {
    PageScanApiJNI.TPSADeviceInfo_Support_MSR_set(swigCPtr, this, value);
  }

  public boolean getSupport_MSR() {
    return PageScanApiJNI.TPSADeviceInfo_Support_MSR_get(swigCPtr, this);
  }

  public void setSupport_Display(boolean value) {
    PageScanApiJNI.TPSADeviceInfo_Support_Display_set(swigCPtr, this, value);
  }

  public boolean getSupport_Display() {
    return PageScanApiJNI.TPSADeviceInfo_Support_Display_get(swigCPtr, this);
  }

  public void setSupport_ExtStatusLed(boolean value) {
    PageScanApiJNI.TPSADeviceInfo_Support_ExtStatusLed_set(swigCPtr, this, value);
  }

  public boolean getSupport_ExtStatusLed() {
    return PageScanApiJNI.TPSADeviceInfo_Support_ExtStatusLed_get(swigCPtr, this);
  }

  public void setSupport_ExtBuzzer(boolean value) {
    PageScanApiJNI.TPSADeviceInfo_Support_ExtBuzzer_set(swigCPtr, this, value);
  }

  public boolean getSupport_ExtBuzzer() {
    return PageScanApiJNI.TPSADeviceInfo_Support_ExtBuzzer_get(swigCPtr, this);
  }

  public void setVersion(int value) {
    PageScanApiJNI.TPSADeviceInfo_Version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return PageScanApiJNI.TPSADeviceInfo_Version_get(swigCPtr, this);
  }

  public void setNumber(int value) {
    PageScanApiJNI.TPSADeviceInfo_Number_set(swigCPtr, this, value);
  }

  public int getNumber() {
    return PageScanApiJNI.TPSADeviceInfo_Number_get(swigCPtr, this);
  }

  public TPSADeviceInfo() {
    this(PageScanApiJNI.new_TPSADeviceInfo(), true);
  }

}
