/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.desko.fullpage;

public class TPSABuzzerSettings2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public TPSABuzzerSettings2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TPSABuzzerSettings2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PageScanApiJNI.delete_TPSABuzzerSettings2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVolume(char value) {
    PageScanApiJNI.TPSABuzzerSettings2_Volume_set(swigCPtr, this, value);
  }

  public char getVolume() {
    return PageScanApiJNI.TPSABuzzerSettings2_Volume_get(swigCPtr, this);
  }

  public void setDuration(int value) {
    PageScanApiJNI.TPSABuzzerSettings2_Duration_set(swigCPtr, this, value);
  }

  public int getDuration() {
    return PageScanApiJNI.TPSABuzzerSettings2_Duration_get(swigCPtr, this);
  }

  public void setHighTime(int value) {
    PageScanApiJNI.TPSABuzzerSettings2_HighTime_set(swigCPtr, this, value);
  }

  public int getHighTime() {
    return PageScanApiJNI.TPSABuzzerSettings2_HighTime_get(swigCPtr, this);
  }

  public void setLowTime(int value) {
    PageScanApiJNI.TPSABuzzerSettings2_LowTime_set(swigCPtr, this, value);
  }

  public int getLowTime() {
    return PageScanApiJNI.TPSABuzzerSettings2_LowTime_get(swigCPtr, this);
  }

  public TPSABuzzerSettings2() {
    this(PageScanApiJNI.new_TPSABuzzerSettings2(), true);
  }

}
